extends: airbnb
env:
  es6: true
  browser: true
  shared-node-browser: true
  jest: true
  serviceworker: true
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 8
  sourceType: module
  # ecmaFeatures:
    # experimentalObjectRestSpread: true
rules:
  arrow-parens: 0
  camelcase: 0
  comma-dangle: warn
  func-names: 0
  import/no-extraneous-dependencies: error
  import/no-useless-path-segments: warn
  import/order: warn
  jsx-a11y/label-has-for: off
  key-spacing: 0
  max-len: 0
  no-alert: 0
  no-continue: 0
  no-console: warn
  no-multi-spaces: 0
  no-param-reassign:
    - error
    - props: false
  no-plusplus: 0
  no-trailing-spaces: warn
  no-use-before-define: [ error, { classes: false, functions: false, variables: false } ]
  no-underscore-dangle: error
  no-unused-vars: error
  object-curly-newline: [ error, { multiline: true }]
  prefer-arrow-callback: warn
  prefer-destructuring: 0
  prefer-const: warn
  prefer-spread: warn
  react/jsx-filename-extension:
    - error
    - extensions:
      - .js
      - .jsx
  react/state-in-constructor: off
  semi: warn
  semi-spacing:
    - warn
    - before: false
      after: true
settings:
  import/resolver:
    node:
      moduleDirectory:
        - src/
        - node_modules
